#!/usr/bin/python

import sys, os, os.path, string, glob, math
import random
import time
import datetime
import tempfile
import subprocess
import unittest
import argparse
import StringIO

parser = argparse.ArgumentParser()
parser.add_argument('infile', type=argparse.FileType('r'), nargs='?', default=sys.stdin)

args = parser.parse_args()

cumtimes = {}

for line in args.infile:
    line = line.strip(' \t\n\r')
    data = line.split()
    t = float(data[1][:-2])
    if t <= 0.0: t = 0.0004
    p = data[0]
    if not cumtimes.has_key(p): cumtimes[p] = 0.0
    cumtimes[p] += t

for k in cumtimes.keys():
    sys.stdout.write("%s  %f\n" % (k, cumtimes[k]))
