#!/usr/bin/python

import sys, os, os.path, string, glob, math
import random
import time
import tempfile
import subprocess
import unittest

class example_test_case(unittest.TestCase):
    def setUp(self):
        sys.stdout.write("Fixture setup!\n")

    def tearDown(self):
        sys.stdout.write("Fixture teardown!\n")

    def test1(self):
        # this unit test should pass
        self.assertEqual(1, 1)

    def test2(self):
        # this unit test should FAIL!
        self.assertEqual(1, 2)

if __name__ == "__main__":
    # this automatically extracts test methods of form 'test*' and runs them
    unittest.main()
